### ISSUE TITLE
Would you consider an API based around phantom types?

### ISSUE THREAD

**Issue by bcpeinhardt** [richard-viney/file_streams#3]
Hey Richard!

I've been using this library as part of doing the codecrafters sqlite gleam challenge, it's been really helpful!!!
I was taking a look at how thing's are structured in v0.5.0, and I noticed you have some functions which return errors if they are called on a file stream which wasn't opened in the correct mode. 

How would you feel about an API where the `FileStream` type uses a subset of its open mode list as a phantom type. This would
for example make calling a function like `read_chars` on a `FileStream` opened in binary mode a compile time error rather than a runtime error, and you could get rid of the `bool.guard` checks.

The upshot is a lot of things that are currently runtime errors become compile time errors.
The downside is the function signatures could become a lot more complex looking (although the call site for the user should be exactly the same).

If I were to experiment with this/make a PR, would you be willing to take a look?

**Comment by richard-viney** [comment]
Hi, glad you've found the library useful!

There are a couple of points here:

* In v0.4 there were separate `ReadStream`/`WriteStream` types and modules, which in some ways is the simplest option as then you can't really go wrong as you get forced to pick a lane. I considered keeping the `ReadStream`, `WriteStream` and `ReadTextStream` modules in v0.5 and implementing them on top of the more generic `FileStream` type that was added, but ultimately decided it wasn't worth the bother. This could be revisited though, i.e. people then only reach for the more powerful behaviour of `FileStream` when actually needed.

* The phantom types might achieve a similar thing in the context of the single `FileStream` type. I believe this wouldn't be possible when opening with the more generic `file_stream.open()` function though, as you don't know what modes were selected. Is there any way around this other than lots of `open_...` functions? If not, one could argue that a smaller number of these functions + runtime errors is preferable. It'd still be possible to misuse these open functions by passing invalid modes etc., so that would need to be checked for.

* Given that you'd want to restrict `read_chars` to text mode files, and there are two cases of these: read-only, and read+write, presumably that means you'd have two phantom types:

```gleam
pub opaque type FileStream(read_mode, write_mode)

pub type FileStreamMode {
  Binary
  Text
  None
}

pub fn open_read(mode: List(FileOpenMode)) -> FileStream(Binary, None) {
  todo
}

pub fn open_write(mode: List(FileOpenMode)) -> FileStream(None, Binary) {
  todo
}

pub fn open_read_write(mode: List(FileOpenMode)) -> FileStream(Binary, Binary) {
  todo
}

pub fn open_read_text(mode: List(FileOpenMode)) -> FileStream(Text, None) {
  todo
}

pub fn open_write_text(mode: List(FileOpenMode)) -> FileStream(None, Text) {
  todo
}

pub fn open_read_write_text(mode: List(FileOpenMode)) -> FileStream(Text, Text) {
  todo
}
```

I'm interested in what the library would look like if it took the above approach, it _might_ be preferable, but I also can't guarantee at this stage that it would be adopted! I don't think such a conversion would take all that long, so if you're interested in trying then we can certainly take a look, either here in in Discord 👍 .

**Comment by bcpeinhardt** [comment]
Just adding a comment here to update you that I'm playing around with this. The idea right now is to have a builder for the file_open_mode rather than providing a list directly. The builder uses phantom types to restrict from creating invalid combinations of file_open_mode options, and since Gleam is completely inferred users on the happy path shouldn't have to look at a single phantom type.
I'll try and make a PR soon so you can take a look and see what you think.

**Comment by richard-viney** [comment]
FYI a number of things have changed in v0.6, including dropping the explicit text mode, the distinction made now is whether `Raw` mode is in use, and the text encoding.

There are also other constraints which would be neat to enforce with phantom types if it's possible, e.g. `read_chars` doesn't work on files opened with `Raw` mode.

**Comment by bcpeinhardt** [comment]
So I explored this with the new options and honestly it's a worse api haha. I think just telling developers to be careful what options they specify is better in this case xD

**Comment by richard-viney** [comment]
Haha ok well thank you for looking into it and also for teaching me more about phantom types!

I do think that a builder pattern for the file modes might still be a worthwhile change even if it's not used for phantom types. What do you think?

**Comment by bcpeinhardt** [comment]
I'm having trouble determining which modes conflict with each other? Could you give a rundown on that?

**Comment by bcpeinhardt** [comment]
I ask because I may have been overdoing the type restrictions haha

**Comment by richard-viney** [comment]
The most obvious one is a read mode is needed to be able to read anything, and similarly for writing. I think if you specify nothing the file stream defaults to reading, but should check this.

The other one is around whether raw mode was specified, and if it not in raw mode, what text encoding was chosen.

In raw mode:

- An `Encoding` can't be part of the file mode when opening a stream.
- `file_stream.set_encoding` can't be used.
- `file_stream.read_chars` can't be used.

Not in raw mode:

- An `Encoding` can be part of the file mode when opening a stream, and defaults to Latin1 if not specified.
- `file_stream.set_encoding` can be used.
- `file_stream.read_chars` can be used.
- Lots of functions can only be used if the active text encoding for the stream is `Latin1`. These are:
  - `file_stream.write_bytes`, `file_system.read_bytes`, `file_system.read_bytes_exact`, `file_stream.read_remaining_bytes`, and all of the helpers that read int/floats of specific width and endianness.

**Comment by richard-viney** [comment]
Any luck?

**Comment by richard-viney** [comment]
I played around with the builder pattern for file modes and in the end didn't think it was worth changing. Most users will use the provided helper functions to open file streams anyway.
